# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
Campaign.destroy_all
Photo.destroy_all

user1 = User.create(name: "Oxfam", location:"London", description:"We are Oxfam", website:"www.oxfam.co.uk", facebook_profile:"oxfam", twitter_profile:"oxfam", role: "charity", password: "password", password_confirmation: "password")
user2 = User.create(name: "British Heart Foundation", location:"London", description:"We are BHF", website:"www.britishheartfundation.co.uk", facebook_profile:"bhf", twitter_profile:"bhf", role: "charity", password: "password", password_confirmation: "password")
user3 = User.create(name:"Médecins Sans Frontières", location:"Paris", description:"We are Médecins Sans Frontières", website:"www.msf.org.uk", facebook_profile:"msf", twitter_profile:"msf", role: "charity", password: "password", password_confirmation: "password")
user4 = User.create(name:"Emergency", location:"Milano", description:"We are Emergency", website:"www.emergencyuk.org", facebook_profile:"emergency", twitter_profile:"emergency", role: "charity", password: "password", password_confirmation: "password")
user5 = User.create(name:"Amnesty International", location:"London", description:"We are Amnesty International", website:"https://www.amnesty.org.uk/", facebook_profile:"amnesty", twitter_profile:"amnesty", role: "charity", password: "password", password_confirmation: "password")
user6 = User.create(username:"", first_name:"", last_name:"", location:"London", description:"", website:"", facebook_profile:"", twitter_profile:"", role: "donor", password: "password", password_confirmation: "password")
user7 = User.create(username:"", first_name:"", last_name:"", location:"London", description:"", website:"", facebook_profile:"", twitter_profile:"", role: "donor", password: "password", password_confirmation: "password")
user8 = User.create(username:"", first_name:"", last_name:"", location:"London", description:"", website:"", facebook_profile:"", twitter_profile:"", role: "donor", password: "password", password_confirmation: "password")
user9 = User.create(username:"", first_name:"", last_name:"", location:"London", description:"", website:"", facebook_profile:"", twitter_profile:"", role: "donor", password: "password", password_confirmation: "password")
user10 = User.create(username:"", first_name:"", last_name:"", location:"London", description:"", website:"", facebook_profile:"", twitter_profile:"", role: "donor", password: "password", password_confirmation: "password")

campaign1 = Campaign.create(title:"A fairer world", description:"The gap between the rich and the rest is spiralling out of control, and standing in the way of ending global poverty.", campaign_logo:"", user_id: user1)
campaign2 = Campaign.create(title:"A cleaner future", description:"When we fight for a global solution to climate change, we help protect millions of people from being forced into hunger.", campaign_logo:"", user_id: user1)
campaign3 = Campaign.create(title:"Safety and dignity", description:"Safety and dignity", description:"When the world's poorest and most vulnerable people are hit by disasters, we help make their voices heard.", campaign_logo:"", user_id: user1)
campaign4 = Campaign.create(title:"MyMarathon", description: "Conquer 26.2 miles throughout September and raise money for life saving heart research.", campaign_logo:"", user_id: user2)
campaign5 = Campaign.create(title:"Just Walk", description:"Walk all over heart disease with Just Walk. Organise a walk and raise money for life saving heart research.", campaign_logo:"", user_id: user2)
campaign6 = Campaign.create(title:"f", description:"e", campaign_logo:"")
campaign7 = Campaign.create(title:"g", description:"d", campaign_logo:"")
campaign8 = Campaign.create(title:"h", description:"c", campaign_logo:"")
campaign9 = Campaign.create(title:"i", description:"b", campaign_logo:"")
campaign10 = Campaign.create(title:"l", description:"a", campaign_logo:"")
photo1 = Photo.create(title:"", location:"", description:"")
photo2 = Photo.create(title:"", location:"", description:"")
photo3 = Photo.create(title:"", location:"", description:"")
photo4 = Photo.create(title:"", location:"", description:"")
photo5 = Photo.create(title:"", location:"", description:"")
photo6 = Photo.create(title:"", location:"", description:"")
photo7 = Photo.create(title:"", location:"", description:"")
photo8 = Photo.create(title:"", location:"", description:"")
photo9 = Photo.create(title:"", location:"", description:"")
photo10 = Photo.create(title:"", location:"", description:"")
photo11 = Photo.create(title:"", location:"", description:"")
photo12 = Photo.create(title:"", location:"", description:"")
photo13 = Photo.create(title:"", location:"", description:"")
photo14 = Photo.create(title:"", location:"", description:"")
photo15 = Photo.create(title:"", location:"", description:"")
photo16 = Photo.create(title:"", location:"", description:"")
photo17 = Photo.create(title:"", location:"", description:"")
photo18 = Photo.create(title:"", location:"", description:"")
photo19 = Photo.create(title:"", location:"", description:"")
photo20 = Photo.create(title:"", location:"", description:"")
photo21 = Photo.create(title:"", location:"", description:"")
photo22 = Photo.create(title:"", location:"", description:"")
photo23 = Photo.create(title:"", location:"", description:"")
photo24 = Photo.create(title:"", location:"", description:"")
photo25 = Photo.create(title:"", location:"", description:"")
photo26 = Photo.create(title:"", location:"", description:"")
photo27 = Photo.create(title:"", location:"", description:"")
photo28 = Photo.create(title:"", location:"", description:"")
photo29 = Photo.create(title:"", location:"", description:"")
photo30 = Photo.create(title:"", location:"", description:"")
photo31 = Photo.create(title:"", location:"", description:"")
photo32 = Photo.create(title:"", location:"", description:"")
photo33 = Photo.create(title:"", location:"", description:"")
photo34 = Photo.create(title:"", location:"", description:"")
photo35 = Photo.create(title:"", location:"", description:"")
photo36 = Photo.create(title:"", location:"", description:"")
photo37 = Photo.create(title:"", location:"", description:"")
photo38 = Photo.create(title:"", location:"", description:"")
photo39 = Photo.create(title:"", location:"", description:"")
photo40 = Photo.create(title:"", location:"", description:"")