# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

user1 = User.create(name: "Oxfam", location:"London", description:"We are Oxfam", website:"www.oxfam.co.uk", facebook_profile:"oxfam", twitter_profile:"oxfam", role: "charity")
user2 = User.create(name: "British Heart Foundation", location:"London", description:"We are BHF", website:"www.britishheartfundation.co.uk", facebook_profile:"bhf", twitter_profile:"bhf", role: "charity")
user3 = User.create(name:"Médecins Sans Frontières", location:"Paris", description:"We are Médecins Sans Frontières", website:"www.msf.org.uk", facebook_profile:"msf", twitter_profile:"msf", role: "charity")
user4 = User.create(name:"Emergency", location:"Milano", description:"We are Emergency", website:"www.emergencyuk.org", facebook_profile:"emergency", twitter_profile:"emergency", role: "charity")
user5 = User.create(name:"Amnesty International", location:"London", description:"We are Amnesty International", website:"https://www.amnesty.org.uk/", facebook_profile:"amnesty", twitter_profile:"amnesty", role: "charity")
user6 = User.create(username:"", first_name:"", last_name:"", location:"London", description:"", website:"https://www.amnesty.org.uk/", facebook_profile:"", twitter_profile:"", role: "donor")
user7 = User.create(username:"", first_name:"", last_name:"", location:"London", description:"", website:"https://www.amnesty.org.uk/", facebook_profile:"", twitter_profile:"", role: "donor")
user8 = User.create(username:"", first_name:"", last_name:"", location:"London", description:"", website:"https://www.amnesty.org.uk/", facebook_profile:"", twitter_profile:"", role: "donor")
user9 = User.create(username:"", first_name:"", last_name:"", location:"London", description:"", website:"https://www.amnesty.org.uk/", facebook_profile:"", twitter_profile:"", role: "donor")
user10 = User.create(username:"", first_name:"", last_name:"", location:"London", description:"", website:"https://www.amnesty.org.uk/", facebook_profile:"", twitter_profile:"", role: "donor")

campaign1 = Campaign.create(title:"", description:"")
campaign2 = Campaign.create(title:"", description:"")
campaign3 = Campaign.create(title:"", description:"")
campaign4 = Campaign.create(title:"", description:"")
campaign5 = Campaign.create(title:"", description:"")
campaign6 = Campaign.create(title:"", description:"")
campaign7 = Campaign.create(title:"", description:"")
campaign8 = Campaign.create(title:"", description:"")
campaign9 = Campaign.create(title:"", description:"")
campaign10 = Campaign.create(title:"", description:"")
photo1 = Photo.create(title:"", location:"", description:"")
photo2 = Photo.create(title:"", location:"", description:"")
photo3 = Photo.create(title:"", location:"", description:"")
photo4 = Photo.create(title:"", location:"", description:"")
photo5 = Photo.create(title:"", location:"", description:"")
photo6 = Photo.create(title:"", location:"", description:"")
photo7 = Photo.create(title:"", location:"", description:"")
photo8 = Photo.create(title:"", location:"", description:"")
photo9 = Photo.create(title:"", location:"", description:"")
photo10 = Photo.create(title:"", location:"", description:"")
photo11 = Photo.create(title:"", location:"", description:"")
photo12 = Photo.create(title:"", location:"", description:"")
photo13 = Photo.create(title:"", location:"", description:"")
photo14 = Photo.create(title:"", location:"", description:"")
photo15 = Photo.create(title:"", location:"", description:"")
photo16 = Photo.create(title:"", location:"", description:"")
photo17 = Photo.create(title:"", location:"", description:"")
photo18 = Photo.create(title:"", location:"", description:"")
photo19 = Photo.create(title:"", location:"", description:"")
photo20 = Photo.create(title:"", location:"", description:"")
photo21 = Photo.create(title:"", location:"", description:"")
photo22 = Photo.create(title:"", location:"", description:"")
photo23 = Photo.create(title:"", location:"", description:"")
photo24 = Photo.create(title:"", location:"", description:"")
photo25 = Photo.create(title:"", location:"", description:"")
photo26 = Photo.create(title:"", location:"", description:"")
photo27 = Photo.create(title:"", location:"", description:"")
photo28 = Photo.create(title:"", location:"", description:"")
photo29 = Photo.create(title:"", location:"", description:"")
photo30 = Photo.create(title:"", location:"", description:"")
photo31 = Photo.create(title:"", location:"", description:"")
photo32 = Photo.create(title:"", location:"", description:"")
photo33 = Photo.create(title:"", location:"", description:"")
photo34 = Photo.create(title:"", location:"", description:"")
photo35 = Photo.create(title:"", location:"", description:"")
photo36 = Photo.create(title:"", location:"", description:"")
photo37 = Photo.create(title:"", location:"", description:"")
photo38 = Photo.create(title:"", location:"", description:"")
photo39 = Photo.create(title:"", location:"", description:"")
photo40 = Photo.create(title:"", location:"", description:"")